rhel:
  hosts:
    rhel-94-openscap.home.lan:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: cloud-user

sles:
  hosts:
    sles-15sp6-openscap.home.lan:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: sles

production:
  children:
    rhel:
    sles:
