rhel:
  hosts:
    oscap-rhel-01.home.lan:
    oscap-rhel-02.home.lan:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: cloud-user

sles:
  hosts:
    oscap-sles-01.home.lan:
    oscap-sles-02.home.lan:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: sles

production:
  children:
    rhel:
    sles:
