---
- name: Remediation for SLES 15 servers
  hosts: sles
  user: root
  gather_facts: false

  tasks:
    - name: Install specific version of packages
      community.general.zypper:
        name: "{{ item }}"
      loop:
        - vim<9.2
        - curl=8.6.0-150600.4.15.1

    - name: Install patches
      community.general.zypper:
        name: "{{ item }}"
        type: patch
      loop:
        - CL-SUSE-SLE-Manager-Tools-15-2018-2441
        - CL-SUSE-SLE-Module-Basesystem-15-SP6-2024-1943
