---
- name: Remediation for RHEL 9 servers
  hosts: rhel
  user: root
  gather_facts: false

  tasks:
    - name: Install the latest version of the package
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - vim <= 8.5
        - curl = 7.76.1-29.el9_4.1
