---
- name: Remediation for RHEL 9 servers
  hosts: rhel
  user: root
  gather_facts: false

  tasks:
    - name: Install the latest version of the package
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - vim <= 8.5
        - curl = 7.76.1-29.el9_4.1

    - name: Find cron files and directories
      ansible.builtin.find:
        paths:
          - /etc
        patterns:
          - cron.hourly
          - cron.daily
          - cron.weekly
          - cron.monthly
          - cron.d
          - crontab
        file_type: any
      register: cron_directories

    - name: Ensure permissions on cron files and directories are configured
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: og-rwx
      with_items: "{{ cron_directories.files }}"
